### PR TITLE
move  mamar database to a repository

### PR DESCRIPTION
**Pull request by Tsugami**

### CODE REVIEW

**Comment by ySnoopyDogy** [comment]
Wasn't better to put it in a function in Users Repositoy as mamar use the same model as Users?

**Comment by Tsugami** [comment]
> Wasn't better to put it in a function in Users Repositoy as mamar use the same model as Users?

look repositories like MVC controller, the controller has only index, show, create, update and delete. in na user controller which of these can be the mamar?

**Comment by Tsugami** [comment]
> > Wasn't better to put it in a function in Users Repositoy as mamar use the same model as Users?
> 
> look repositories like MVC controller, the controller has only index, show, create, update and delete. in an user controller which of these can be the `mamar`?

MVC has is pattern for not

**Comment by Tsugami** [comment]
> > Wasn't better to put it in a function in Users Repositoy as mamar use the same model as Users?
> 
> look repositories like MVC controller, the controller has only index, show, create, update and delete. in an user controller which of these can be the `mamar`?

mvc has this pattern to not have more than one topic in the controller. The repository pattern follows the same principle. a repository is not a function group that interact with only an database table, repository is an function gruop that interact with a topic in database.

**Pull request merged**
